"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.appRouterV1 = void 0;
const controllers_1 = require("../../controllers");
const userRouter_1 = require("./userRouter");
const uploadFileRoute_1 = require("./uploadFileRoute");
const myProfileRouter_1 = require("./myProfileRouter");
const deviceRouter_1 = require("./deviceRouter");
const devicePortRouter_1 = require("./devicePortRouter ");
const statisticRoute_1 = require("./statisticRoute");
const buildingRouter_1 = require("./buildingRouter");
const roomRouter_1 = require("./roomRouter");
const reportRouter_1 = require("./reportRouter");
const devicePortLogsRouter_1 = require("./devicePortLogsRouter");
const floorRouter_1 = require("./floorRouter");
const layoutRouter_1 = require("./layoutRouter");
const deviceChartRouter_1 = require("./deviceChartRouter");
const broadcastRouter_1 = require("./broadcastRouter");
const settingRouter_1 = require("./settingRouter");
const appRouterV1 = (app) => {
    app.get('/api/v1', async (req, res) => await (0, controllers_1.index)(req, res));
    (0, userRouter_1.userRoutes)(app);
    (0, uploadFileRoute_1.uploadFileRoutes)(app);
    (0, statisticRoute_1.statisticRouter)(app);
    (0, myProfileRouter_1.myProfileRouter)(app);
    (0, deviceRouter_1.deviceRouter)(app);
    (0, devicePortRouter_1.devicePortRouter)(app);
    (0, floorRouter_1.floorRouter)(app);
    (0, roomRouter_1.roomRouter)(app);
    (0, buildingRouter_1.buildingRouter)(app);
    (0, reportRouter_1.reportRouter)(app);
    (0, devicePortLogsRouter_1.devicePortLogRouter)(app);
    (0, layoutRouter_1.layoutRouter)(app);
    (0, deviceChartRouter_1.deviceChartRouter)(app);
    (0, broadcastRouter_1.broadcastRouter)(app);
    (0, settingRouter_1.settingRouter)(app);
};
exports.appRouterV1 = appRouterV1;
